=== fermi-lat/Interleave/xml/backgroundInterleave.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : backgroundInterleave.xsd
    Created on : October 30, 2006, 2:05 PM
    Author     : dflath
    Description:
        Definition of valid xml to describe a background source or list of sources.
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
   xmlns:ns="http://xml.netbeans.org/examples/targetNS"
   targetNamespace="http://xml.netbeans.org/examples/targetNS"
   xmlns="http://xml.netbeans.org/examples/targetNS"
   elementFormDefault="qualified">

   <xsd:element name="sourceList">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element ref="source" maxOccurs="unbounded"/>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>

   <xsd:element name="source">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element ref="bin" maxOccurs="unbounded"/>
         </xsd:sequence>

<!-- TODO:  maybe later we want to replace these by enumerated types, as in commented sections immediately below and at end of document -->         
         <xsd:attribute name="name" type="xsd:string" use="required"/>
         <xsd:attribute name="type" type="xsd:string" use="required"/>
         <xsd:attribute name="rangeUnits" type="xsd:string" use="required"/>
<!--
         <xsd:attribute name="name" type="NameType" use="required"/>
         <xsd:attribute name="type" type="SourceType" use="required"/>
         <xsd:attribute name="rangeUnits" type="RangeUnitType" use="required"/>
-->         
         <xsd:attribute name="rangeMin" type="xsd:decimal" use="required"/>
         <xsd:attribute name="rangeMax" type="xsd:decimal" use="required"/>
      </xsd:complexType>
   </xsd:element>
   
   <xsd:element name="bin">
      <xsd:complexType>
         <xsd:choice>
            <xsd:element ref="fileList"/>
            <xsd:element ref="eventList"/>
         </xsd:choice>
         <xsd:attribute name="min" type="xsd:decimal" use="required"/>
         <xsd:attribute name="max" type="xsd:decimal" use="required"/>
         <xsd:attribute name="triggerRate" type="xsd:decimal" use="required"/>
         <xsd:attribute name="downlinkRate" type="xsd:decimal" use="required"/>
      </xsd:complexType>
   </xsd:element>
   
   <xsd:element name="fileList">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element ref="file" maxOccurs="unbounded"/>
         </xsd:sequence>
      </xsd:complexType>      
   </xsd:element>
   
   <xsd:element name="file">
      <xsd:complexType>
            <xsd:attribute name="filePath" type="xsd:string" use="required"/>
            <xsd:attribute name="treeName" type="xsd:string" use="required"/>
            <xsd:attribute name="numEvents" type="xsd:integer" use="required"/>
      </xsd:complexType>      
   </xsd:element>
   
   <xsd:element name="eventList">
      <xsd:complexType  mixed="true">
         <xsd:sequence>
            <xsd:element ref="event" maxOccurs="unbounded"/>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>

   <xsd:element name="event">
      <xsd:complexType>
            <xsd:attribute name="filePath" type="xsd:string" use="required"/>
            <xsd:attribute name="treeName" type="xsd:string" use="required"/>
            <xsd:attribute name="eventIndex" type="xsd:integer" use="required"/>
      </xsd:complexType>      
   </xsd:element>

<!--   
   <xsd:simpleType name="NameType">
      <xsd:restriction base="xsd:NMTOKEN">
         <xsd:enumeration value="boolean"/>
         <xsd:enumeration value="integer"/>
         <xsd:enumeration value="float"/>
         <xsd:enumeration value="string"/>
      </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="SourceType">
      <xsd:restriction base="xsd:NMTOKEN">
         <xsd:enumeration value="boolean"/>
         <xsd:enumeration value="integer"/>
         <xsd:enumeration value="float"/>
         <xsd:enumeration value="string"/>
      </xsd:restriction>
   </xsd:simpleType>
   <xsd:simpleType name="RangeUnitType">
      <xsd:restriction base="xsd:NMTOKEN">
         <xsd:enumeration value="boolean"/>
         <xsd:enumeration value="integer"/>
         <xsd:enumeration value="float"/>
         <xsd:enumeration value="string"/>
      </xsd:restriction>
   </xsd:simpleType>
-->
</xsd:schema>

=== fermi-lat/Interleave/xml/exampleBackgroundSet.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : exampleBackgroundSet.xml
    Created on : October 30, 2006, 3:43 PM
    Author     : dflath
    Description:
        Purpose of the document follows.
-->

<sourceList xmlns='http://xml.netbeans.org/examples/targetNS'
  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
  xsi:schemaLocation='http://xml.netbeans.org/examples/targetNS file:/./backgroundInterleave.xsd'>

   <source name="earthsLimb" type="PtSCzenith" rangeUnits="degrees" rangeMin="-180" rangeMax="180.0">
      <bin min="-180" max="89." triggerRate="100.0" downlinkRate="0.1">
         <fileList>
            <file filePath="$(ROOTTESTDATAROOT)/data/default/merit.root" treeName="MeritTuple" numEvents="5"/>
         </fileList>
      </bin>
      <bin min="89" max="91" triggerRate="200.0" downlinkRate="0.2">
         <fileList>
            <file filePath="$(ROOTTESTDATAROOT)/data/default/merit.root" treeName="MeritTuple" numEvents="5"/>
         </fileList>
      </bin>
      <bin min="91" max="180." triggerRate="300.0" downlinkRate="0.3">
         <fileList>
            <file filePath="$(ROOTTESTDATAROOT)/data/default/merit.root" treeName="MeritTuple" numEvents="5"/>
         </fileList>
      </bin>
   </source>

   <source name="diffuse" type="PtMagLat" rangeUnits="degrees" rangeMin="-45" rangeMax="45.0">
      <bin min="-45." max="45.0" triggerRate="3000.0" downlinkRate="0.2">
         <fileList>
         <!-- two copies -->
            <file filePath="$(ROOTTESTDATAROOT)/data/default/merit.root" treeName="MeritTuple" numEvents="5"/>
            <file filePath="$(ROOTTESTDATAROOT)/data/default/merit.root" treeName="MeritTuple" numEvents="5"/>
         </fileList>
      </bin>
   </source>      
</sourceList>
